export const IS_SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SET_LOADING = "SET_LOADING";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_SINGLE_PRODUCT_LOADING = "SET_SINGLE_PRODUCT_LOADING";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
/*
  GET_SINGLE_PRODUCT_BEGIN,
  GET_SINGLE_PRODUCT_SUCCESS,
  GET_SINGLE_PRODUCT_ERROR,
  seklinde yazacagdg ama biz simple tutag deye tek yazdg
*/
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const CLEAR_SHOPPING = "CLEAR_SHOPPING";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const TOGGLE_CART_ITEM_AMOUNT = "  TOGGLE_CART_ITEM_AMOUNT";

//actions for filtering products
export const GET_ALL_PRODUCTS_TOBE_FILTERED = "GET_ALL_PRODUCTS_TOBE_FILTERED";
export const UPDATE_SORT_VALUE = "UPDATE_SORT_VALUE";
export const SORT_PRODUCTS_BY = "SORT_PRODUCTS_BY";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTER = "CLEAR_FILTER";
